# Site Settings
title: Shoe Angel Footwear Programs
email: chris.mounce@rockybrands.com
description: Footwear Programs benefiting Medical Professionals and the communities they serve.
baseurl: ""
url: "https://crmounce.github.io/"
github_username:  crmounce
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
navigation:
- text: About
  url: /about/
- text: Brands
  url: /brands/
- text: Donations
  url: /donations/
- text: FAQs
  url: /faq/
- text: Contact
  url: /contact/
- text: Login
  url: https://www.google.com/
